spring:
  application:
    name: poc-rimborsi-producer
  datasource:
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 2
    url: jdbc:postgresql://internal-aa715dcc4c9204fbdb784093946259c3-972620278.eu-west-1.elb.amazonaws.com:5432/nart_anag
    username: exp
    password: exp
    driverClassName: org.postgresql.Driver
  sql:
    init:
      platform: postgres
